[package]
name = "zerod"
version = "0.1.0"
authors = ["Alex Lyon <arcterus@mail.com>"]
edition = "2021"

[dependencies]
redox_syscall = "0.4.1"
redox-scheme = { git = "https://gitlab.redox-os.org/redox-os/redox-scheme.git" }
redox-daemon = "0.1.2"
libredox = "0.0.3"
